### ISSUE TITLE
Fake node selection fails

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/Sequencer#39]
From the log:

2015-02-26 20:11:54,498 : NetworkPlan [INFO] : Asserting Input Projections Match
2015-02-26 20:11:54,502 : NetworkPlan [INFO] : Aligning Network Nodes With Input Metrics
Traceback (most recent call last):
  File "/home/mr/model_runner/scripts/mvmax_sequencer.py", line 19, in <module>
    nwp = NetworkPlan(shp_file, csv_file, prioritize='Population')
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/sequencer/NetworkPlan.py", line 54, in __init__
    loc_tol = self.TOL
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/sequencer/Utils.py", line 59, in prep_data
    fake_nodes = node_df.ix[node_df.index - closest_match.index]
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/pandas/core/index.py", line 2131, in _evaluate_numeric_binop
    raise ValueError("cannot evaluate a numeric op with unequal lengths")
ValueError: cannot evaluate a numeric op with unequal lengths

**Comment by chrisnatali** [comment]
Retrieve input file that generated this result from:  http://23.253.67.58:8000/data/b3585843-79a4-4965-9baa-fa0b15252a53/input.zip
