### ISSUE TITLE
Mysterious input error

### ISSUE THREAD

**Issue by vr2262** [SEL-Columbia/Sequencer#53]
```
$ python mvmax_sequencer.py -i input -o output                                                                                
2016-04-15 13:06:25,590 - sequencer - INFO - sequencer 0.0.5 (Python 2.7.11)
2016-04-15 13:06:25,591 - sequencer - INFO - Asserting Input Projections Match
Traceback (most recent call last):
  File "mvmax_sequencer.py", line 33, in <module>
    nwp = NetworkPlan(shp_file, csv_file, prioritize='Population')
  File "/home/.../Sequencer/sequencer/NetworkPlan.py", line 39, in __init__
    self._assert_proj_match(shp, csv)
  File "/home/.../Sequencer/sequencer/NetworkPlan.py", line 117, in _assert_proj_match
    self.proj = shapefile.crs['proj']
KeyError: 'proj'
```

**Comment by vr2262** [comment]
Also (if it helps), when it fails the value of `shapefile.crs` is `{'init': u'epsg:4326'}`.

**Comment by chrisnatali** [comment]
I *think* this has to do with a library version incompatibility (gdal or fiona).  

Didn't this run without this error on that problematic dataset?  If so, what changed?

**Comment by vr2262** [comment]
Oh... I think something else I installed into the virtualenv may be the culprit...

**Comment by vr2262** [comment]
Yes... When I installed matplotlib it upgraded fiona. You should update Sequencer to use the newest packages!

**Comment by chrisnatali** [comment]
Cool.  Thanks.
